class User {
  constructor(id, name, gender, contact, preference) {
    this.id = id; // represents the id generated by the firestore
    this.name = name;
    this.gener = gender;
    this.contact = contact;
    this.preference = preference;
  }
}

module.exports = User;
